## Imports

In [1]:
import pandas as pd
import numpy as np

## Data Profiling

In [2]:
users = pd.read_csv("../data/users.csv")
print(users.shape)

pd.DataFrame({
    "dtype": users.dtypes,
    "null_count": users.isna().sum(),
    "unique_counts": users.nunique()
})

(20000, 4)

                     dtype  null_count  unique_counts
user_id              int64           0          20000
signup_date            str           0            540
city                   str           0              6
acquisition_channel    str           0              4

In [3]:
orders = pd.read_csv("../data/orders.csv")
print(orders.shape)

pd.DataFrame({
    "dtype": orders.dtypes,
    "null_count": orders.isna().sum(),
    "unique_counts": orders.nunique()
})

(96020, 9)

                dtype  null_count  unique_counts
order_id        int64           0          96020
user_id         int64           0          17161
store_id          str           0             48
city              str           0              6
order_ts          str           0          85953
items           int64           0             15
gmv           float64           0          57314
delivery_min  float64           0            366
category          str           0              6

In [4]:
orders.head()

,order_id,user_id,store_id,city,order_ts,items,gmv,delivery_min,category
0,1,10700,MUM-07,Mumbai,2025-01-02 10:44:00,5,155.93,20.9,dairy
1,2,8110,DEL-03,Delhi,2025-01-06 07:09:00,2,123.86,11.9,pharmacy
2,3,15650,PUN-01,Pune,2025-01-06 15:27:00,2,184.46,16.8,pharmacy
3,4,1908,DEL-07,Delhi,2025-01-08 13:06:00,8,395.88,24.6,pharmacy
4,5,2751,BEN-07,Bengaluru,2025-01-08 14:57:00,5,199.17,21.8,grocery

In [5]:
store_city_mapping = orders[["city", "store_id"]].drop_duplicates()
store_city_mapping = store_city_mapping.sort_values(by = ["city", "store_id"], ascending = [True, True])
store_city_mapping

          city store_id
48   Bengaluru   BEN-01
34   Bengaluru   BEN-02
15   Bengaluru   BEN-03
97   Bengaluru   BEN-04
38   Bengaluru   BEN-05
19   Bengaluru   BEN-06
4    Bengaluru   BEN-07
49   Bengaluru   BEN-08
156      Delhi   DEL-01
73       Delhi   DEL-02
1        Delhi   DEL-03
68       Delhi   DEL-04
8        Delhi   DEL-05
30       Delhi   DEL-06
3        Delhi   DEL-07
21       Delhi   DEL-08
85    Gurugram   GUR-01
5     Gurugram   GUR-02
28    Gurugram   GUR-03
168   Gurugram   GUR-04
54    Gurugram   GUR-05
16    Gurugram   GUR-06
17    Gurugram   GUR-07
70    Gurugram   GUR-08
7    Hyderabad   HYD-01
6    Hyderabad   HYD-02
135  Hyderabad   HYD-03
268  Hyderabad   HYD-04
113  Hyderabad   HYD-05
175  Hyderabad   HYD-06
108  Hyderabad   HYD-07
158  Hyderabad   HYD-08
22      Mumbai   MUM-01
59      Mumbai   MUM-02
10      Mumbai   MUM-03
57      Mumbai   MUM-04
43      Mumbai   MUM-05
25      Mumbai   MUM-06
0       Mumbai   MUM-07
76      Mumbai   MUM-08
2         Pune   PUN-01
37        Pune   PUN-02
18        Pune   PUN-03
134       Pune   PUN-04
13        Pune   PUN-05
29        Pune   PUN-06
33        Pune   PUN-07
12        Pune   PUN-08

In [6]:
experiment = pd.read_csv("../data/experiment.csv")
print(experiment.shape)

pd.DataFrame({
    "dtype": experiment.dtypes,
    "null_count": experiment.isna().sum(),
    "unique_counts": experiment.nunique()
})

(12000, 6)

                 dtype  null_count  unique_counts
user_id          int64           0          12000
variant            str           0              2
exposure_date      str           0             14
pre_gmv_28d    float64           0           8662
orders_14d       int64           0             19
gmv_14d        float64           0           7130

In [7]:
users['signup_date'] = pd.to_datetime(users['signup_date'])
orders['order_ts'] = pd.to_datetime(orders['order_ts'])
experiment['exposure_date'] = pd.to_datetime(experiment['exposure_date'])

In [8]:
# Runtime of experiment
print(f"Experiment ran from {experiment['exposure_date'].min().date()} till {experiment['exposure_date'].max().date()}")

Experiment ran from 2026-09-01 till 2026-09-14

In [9]:
# Orders data
print(f"Orders data is from {orders['order_ts'].min().date()} till {orders['order_ts'].max().date()}")

Orders data is from 2025-01-02 till 2026-09-29

In [10]:
# Users signup dates
print(f"Users belongs to {users['signup_date'].min().date()} till {users['signup_date'].max().date()} date range")

Users belongs to 2025-01-01 till 2026-06-24 date range

In [11]:
users_rows = len(users)
unique_users = users['user_id'].nunique()
print(f"Users base has {unique_users} users")

if users_rows == unique_users:
    print("This ensures uniqueness of user_id in users base")
else:
    print("Users base user_id isn't unique")

Users base has 20000 users
This ensures uniqueness of user_id in users base

In [12]:
experiment_rows = len(experiment)
unique_experiment_users = experiment['user_id'].nunique()
print(f"Experiments base has {unique_experiment_users} users")

if experiment_rows == unique_experiment_users:
    print("This ensures uniqueness of user_id in experiment base")
else:
    print("Experiment base user_id isn't unique")

Experiments base has 12000 users
This ensures uniqueness of user_id in experiment base

In [13]:
print(f"Number of users in orders: {orders['user_id'].nunique()}")

Number of users in orders: 17161

In [14]:
orders = orders.merge(users, on = "user_id", how = "left", suffixes = ("_orders", "_users"))

acquisition_order_summary = (
    orders
    .groupby(["acquisition_channel"], as_index = False)
    .agg(
        users = ("user_id", "nunique"),
        orders = ("order_id", "count"),
        gmv = ("gmv", "sum")
    )
)

acquisition_order_summary["order_frequency"] = acquisition_order_summary["orders"]/acquisition_order_summary["users"]
acquisition_order_summary["average_order_value"] = acquisition_order_summary["gmv"]/acquisition_order_summary["users"]

acquisition_order_summary

,acquisition_channel,users,orders,gmv,order_frequency,average_order_value
0,organic,7751,43333,18565754.73,5.590633,2395.272188
1,paid_social,4282,23869,10259255.06,5.574264,2395.902630
2,referral,2543,14251,6082651.72,5.604011,2391.919670
3,search,2585,14567,6219598.48,5.635203,2406.034228

In [15]:
len(orders[orders["city_orders"] != orders["city_users"]])

0

In [16]:
city_order_summary = (
    orders
    .groupby(["city_orders"], as_index = False)
    .agg(
        users = ("user_id", "nunique"),
        orders = ("order_id", "count"),
        gmv = ("gmv", "sum")
    )
)

city_order_summary["order_frequency"] = city_order_summary["orders"]/city_order_summary["users"]
city_order_summary["average_order_value"] = city_order_summary["gmv"]/city_order_summary["users"]

city_order_summary

,city_orders,users,orders,gmv,order_frequency,average_order_value
0,Bengaluru,4223,24173,10392722.49,5.724130,2460.980935
1,Delhi,4177,22899,9781073.77,5.482164,2341.650412
2,Gurugram,1759,9746,4168862.16,5.540648,2370.018283
3,Hyderabad,1762,9878,4260769.00,5.606129,2418.143587
4,Mumbai,3483,19404,8297482.06,5.571059,2382.280235
5,Pune,1757,9920,4226350.51,5.645987,2405.435692

In [17]:
print(orders['gmv'].quantile([0.5, 0.9, 0.99, 1]))

0.50     343.7850
0.90     817.4610
0.99    1620.5149
1.00    5032.8300
Name: gmv, dtype: float64

In [18]:
print(orders['delivery_min'].quantile([0.5, 0.9, 0.99, 1]))

0.50    15.3
0.90    22.5
0.99    30.3
1.00    45.3
Name: delivery_min, dtype: float64

In [19]:
store_summary = orders.groupby('store_id').agg(
    order_count=('order_id', 'count'),          # Number of orders (assumes 'order_id' is your primary key)
    total_gmv=('gmv', 'sum'),                    # Total Gross Merchandise Value
    unique_users=('user_id', 'nunique'),         # Number of unique users
    p50_delivery=('delivery_min', lambda x: x.quantile(0.50)),
    p90_delivery=('delivery_min', lambda x: x.quantile(0.90)),
    p99_delivery=('delivery_min', lambda x: x.quantile(0.99)),
    max_delivery=('delivery_min', 'max')         # 1.0 quantile is just the maximum value
)

store_summary

,order_count,total_gmv,unique_users,p50_delivery,p90_delivery,p99_delivery,max_delivery
store_id,,,,,,,
BEN-01,3017,1257483.94,1928,15.1,22.30,30.200,38.2
BEN-02,3114,1322807.08,1973,15.3,22.57,30.300,42.9
BEN-03,3033,1310569.50,1903,15.5,22.70,31.068,45.3
BEN-04,3013,1310135.24,1908,15.4,22.50,29.988,42.8
BEN-05,2981,1301647.30,1935,15.5,22.50,30.420,44.3
BEN-06,3121,1369130.47,1978,15.4,22.60,30.980,39.7
BEN-07,2939,1261571.60,1874,15.4,22.72,30.748,42.8
BEN-08,2955,1259377.36,1926,15.4,22.76,29.500,36.5
DEL-01,2870,1229749.16,1852,15.6,22.51,30.731,40.8
DEL-02,2919,1240592.45,1836,15.3,22.42,30.382,40.4
DEL-03,2845,1228338.10,1836,15.2,22.30,29.612,39.6
DEL-04,2836,1201453.87,1817,15.2,22.30,29.565,39.3
DEL-05,2860,1209548.64,1860,15.3,23.00,30.341,43.0
DEL-06,2851,1199552.50,1876,15.3,22.70,29.700,44.1
DEL-07,2849,1251133.66,1852,15.3,22.20,29.900,36.9
DEL-08,2869,1220705.39,1857,15.3,22.12,30.396,41.5
GUR-01,1268,530179.68,799,15.0,22.00,30.298,37.9
GUR-02,1208,523711.82,786,15.1,22.50,30.286,37.7
GUR-03,1218,537811.30,790,15.2,22.70,30.066,37.8
GUR-04,1178,499869.42,769,15.5,22.73,30.369,38.9
GUR-05,1227,527030.33,775,15.3,23.20,30.974,35.5
GUR-06,1247,529912.98,790,15.6,22.90,29.808,38.1
GUR-07,1196,509401.98,766,15.4,23.10,31.500,35.1
GUR-08,1204,510944.65,773,15.4,22.07,29.697,37.8
HYD-01,1202,523807.64,785,15.4,22.70,30.998,44.1
HYD-02,1273,549912.10,799,15.2,22.60,30.528,36.2
HYD-03,1283,551666.87,822,15.5,22.70,29.136,34.7
HYD-04,1180,515780.48,764,15.6,22.50,29.947,43.4
HYD-05,1306,556345.80,810,15.5,22.90,31.890,42.3
HYD-06,1193,513051.11,758,15.0,21.98,30.748,42.1
HYD-07,1229,530722.84,780,15.4,22.80,29.100,38.9
HYD-08,1212,519482.16,790,15.1,22.30,30.389,35.7
MUM-01,2454,1063862.90,1596,15.2,22.67,29.294,39.8
MUM-02,2435,1025156.17,1537,15.4,22.60,30.000,40.3
MUM-03,2449,1047162.87,1589,15.5,22.70,30.756,43.0
MUM-04,2451,1032661.37,1573,15.2,22.40,29.550,41.9
MUM-05,2341,997507.08,1533,15.2,22.50,30.300,43.0
MUM-06,2483,1063944.43,1556,15.3,22.60,29.918,42.8
MUM-07,2347,1005713.21,1513,15.2,22.30,29.400,38.1
MUM-08,2444,1061474.03,1568,15.4,22.30,30.000,39.4
PUN-01,1239,523647.18,809,15.2,22.60,29.720,38.0
PUN-02,1273,564301.96,824,15.2,21.98,29.568,34.5
PUN-03,1220,522475.92,796,15.3,22.40,28.600,36.9
PUN-04,1182,488965.75,779,15.6,22.59,30.876,43.2
PUN-05,1276,542469.16,811,15.2,22.50,29.725,41.2
PUN-06,1259,532436.42,843,15.3,22.30,29.352,43.1
PUN-07,1272,546285.03,811,15.3,22.00,29.245,40.9
PUN-08,1199,505769.09,765,15.3,22.10,30.802,37.8

In [20]:
orders_rows = len(orders)
unique_orders = orders['order_id'].nunique()
print(f"Orders base has {unique_orders} orders")

if orders_rows == unique_orders:
    print("This ensures uniqueness of order_id in orders base")
else:
    print("Orders base order_id isn't unique")

Orders base has 96020 orders
This ensures uniqueness of order_id in orders base

Number of orders in orders table is 96020 and we are able to deliver 99% of them in 30 minutes

### Things I'd ask the data owner about
1. pre_gmv_28d, orders_14d, gmv_14d - are these related to exposure_date? if yes then what time?
2. order_ts column, is this UTC or IST?
3. How come we are getting more orders from Organic channel instead of pain one? Is this correct? If yes, then we might need to work on marketing.
4. Each city has 8 stores, even though we are getting significantly more orders from Bengaluru and Delhi. Is there any plan to open more stores in these cities?
5. All of our stores are delivering 99% of orders within 30 minutes, that's good performance. Are we sure, delivery done is being marked only after delivered to customer. Riders aren't marked delivered by themselves to reach the targets?